[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "ts-atbuilding-csc"
description = "ATBuilding dome vent CSC."
license = { text = "GPL" }
classifiers = [ "Programming Language :: Python :: 3" ]
readme = "README.rst"
urls = { source_code = "https://github.com/lsst-ts/ts_atbuilding_csc" }
dynamic = ["version"]

[tool.setuptools.dynamic]
version = { attr = "setuptools_scm.get_version" }

[tool.setuptools.packages.find]
where = [ "python" ]

[project.scripts]
run_atbuilding = "lsst.ts.atbuilding.csc:run_atbuilding"

[tool.setuptools_scm]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[project.optional-dependencies]
dev = ["documenteer[pipelines]"]
